### ISSUE TITLE
通过cocoa安转不了

### ISSUE THREAD

**Issue by zhangjiang1203** [Assuner-Lee/LPDQuoteImagesView#2]
pg$ pod search LPDQuoteImagesView
[!] Unable to find a pod with name, author, summary, or description matching `LPDQuoteImagesView` 这个问题更新一下

**Comment by Assuner-Lee** [comment]
目前确实搜不到 ，但可以通过pod install直接安装，可以安装成功

**Comment by Assuner-Lee** [comment]
正在解决这个问题

**Comment by Assuner-Lee** [comment]
知道了，原因是你的本地的Specs没有更新，你去cocoapods官网是可以搜到的

**Comment by Assuner-Lee** [comment]
或者过段日子就能用pod search搜到了
