### ISSUE TITLE
还不如直接把链接给上呢

### ISSUE THREAD

**Issue by iosyezichongling** [Assuner-Lee/LPDQuoteImagesView#3]
抄人家T大神的有意思吗？

**Comment by Assuner-Lee** [comment]
我这个本来就是垃圾库，写着玩的，封装完使用倒是很方便，谢谢你的提醒，我要把来源于TZ写的更明显点

**Comment by zhangjiang1203** [comment]
这个在设置语言的时候图片的获取会有问题，你的判断是字符串，比如说  delete或者最近删除 这个语言改变了 就获取不到图片了

**Comment by Assuner-Lee** [comment]
我看下
